[
  :program
  [
    [
      :class
      [
        :const_ref
        [
          :@const
          "Pythagoras"
          [
            1
            6
          ]
        ]
      ]
      nil
      [
        :body_stmt
        [
          [
            :def
            [
              :@ident
              "hypotenuse"
              [
                2
                6
              ]
            ]
            [
              :paren
              [
                :params
                [
                  [
                    :@ident
                    "a"
                    [
                      2
                      17
                    ]
                  ]
                  [
                    :@ident
                    "b"
                    [
                      2
                      20
                    ]
                  ]
                ]
                nil
                nil
                nil
                nil
              ]
            ]
            [
              :body_stmt
              [
                [
                  :method_add_arg
                  [
                    :fcall
                    [
                      :@ident
                      "square_root"
                      [
                        3
                        4
                      ]
                    ]
                  ]
                  [
                    :arg_paren
                    [
                      :args_add_block
                      [
                        [
                          :method_add_arg
                          [
                            :fcall
                            [
                              :@ident
                              "sum_of_squares"
                              [
                                3
                                16
                              ]
                            ]
                          ]
                          [
                            :arg_paren
                            [
                              :args_add_block
                              [
                                [
                                  :var_ref
                                  [
                                    :@ident
                                    "a"
                                    [
                                      3
                                      31
                                    ]
                                  ]
                                ]
                                [
                                  :var_ref
                                  [
                                    :@ident
                                    "b"
                                    [
                                      3
                                      34
                                    ]
                                  ]
                                ]
                              ]
                              false
                            ]
                          ]
                        ]
                      ]
                      false
                    ]
                  ]
                ]
              ]
              nil
              nil
              nil
            ]
          ]
          [
            :def
            [
              :@ident
              "square_root"
              [
                5
                6
              ]
            ]
            [
              :paren
              [
                :params
                [
                  [
                    :@ident
                    "x"
                    [
                      5
                      18
                    ]
                  ]
                ]
                nil
                nil
                nil
                nil
              ]
            ]
            [
              :body_stmt
              [
                [
                  :method_add_arg
                  [
                    :call
                    [
                      :var_ref
                      [
                        :@const
                        "Math"
                        [
                          6
                          4
                        ]
                      ]
                    ]
                    :"."
                    [
                      :@ident
                      "sqrt"
                      [
                        6
                        10
                      ]
                    ]
                  ]
                  [
                    :arg_paren
                    [
                      :args_add_block
                      [
                        [
                          :var_ref
                          [
                            :@ident
                            "x"
                            [
                              6
                              15
                            ]
                          ]
                        ]
                      ]
                      false
                    ]
                  ]
                ]
              ]
              nil
              nil
              nil
            ]
          ]
          [
            :def
            [
              :@ident
              "sum_of_squares"
              [
                8
                6
              ]
            ]
            [
              :paren
              [
                :params
                [
                  [
                    :@ident
                    "a"
                    [
                      8
                      21
                    ]
                  ]
                  [
                    :@ident
                    "b"
                    [
                      8
                      24
                    ]
                  ]
                ]
                nil
                nil
                nil
                nil
              ]
            ]
            [
              :body_stmt
              [
                [
                  :method_add_arg
                  [
                    :fcall
                    [
                      :@ident
                      "sum"
                      [
                        9
                        4
                      ]
                    ]
                  ]
                  [
                    :arg_paren
                    [
                      :args_add_block
                      [
                        [
                          :method_add_arg
                          [
                            :fcall
                            [
                              :@ident
                              "square"
                              [
                                9
                                8
                              ]
                            ]
                          ]
                          [
                            :arg_paren
                            [
                              :args_add_block
                              [
                                [
                                  :var_ref
                                  [
                                    :@ident
                                    "a"
                                    [
                                      9
                                      15
                                    ]
                                  ]
                                ]
                              ]
                              false
                            ]
                          ]
                        ]
                        [
                          :method_add_arg
                          [
                            :fcall
                            [
                              :@ident
                              "square"
                              [
                                9
                                19
                              ]
                            ]
                          ]
                          [
                            :arg_paren
                            [
                              :args_add_block
                              [
                                [
                                  :var_ref
                                  [
                                    :@ident
                                    "b"
                                    [
                                      9
                                      26
                                    ]
                                  ]
                                ]
                              ]
                              false
                            ]
                          ]
                        ]
                      ]
                      false
                    ]
                  ]
                ]
              ]
              nil
              nil
              nil
            ]
          ]
          [
            :def
            [
              :@ident
              "sum"
              [
                11
                6
              ]
            ]
            [
              :paren
              [
                :params
                [
                  [
                    :@ident
                    "a"
                    [
                      11
                      10
                    ]
                  ]
                  [
                    :@ident
                    "b"
                    [
                      11
                      13
                    ]
                  ]
                ]
                nil
                nil
                nil
                nil
              ]
            ]
            [
              :body_stmt
              [
                [
                  :binary
                  [
                    :var_ref
                    [
                      :@ident
                      "a"
                      [
                        12
                        4
                      ]
                    ]
                  ]
                  :+
                  [
                    :var_ref
                    [
                      :@ident
                      "b"
                      [
                        12
                        8
                      ]
                    ]
                  ]
                ]
              ]
              nil
              nil
              nil
            ]
          ]
          [
            :def
            [
              :@ident
              "square"
              [
                14
                6
              ]
            ]
            [
              :paren
              [
                :params
                [
                  [
                    :@ident
                    "x"
                    [
                      14
                      13
                    ]
                  ]
                ]
                nil
                nil
                nil
                nil
              ]
            ]
            [
              :body_stmt
              [
                [
                  :method_add_arg
                  [
                    :fcall
                    [
                      :@ident
                      "multiply"
                      [
                        15
                        4
                      ]
                    ]
                  ]
                  [
                    :arg_paren
                    [
                      :args_add_block
                      [
                        [
                          :var_ref
                          [
                            :@ident
                            "x"
                            [
                              15
                              13
                            ]
                          ]
                        ]
                        [
                          :var_ref
                          [
                            :@ident
                            "x"
                            [
                              15
                              16
                            ]
                          ]
                        ]
                      ]
                      false
                    ]
                  ]
                ]
              ]
              nil
              nil
              nil
            ]
          ]
          [
            :def
            [
              :@ident
              "multiply"
              [
                17
                6
              ]
            ]
            [
              :paren
              [
                :params
                [
                  [
                    :@ident
                    "a"
                    [
                      17
                      15
                    ]
                  ]
                  [
                    :@ident
                    "b"
                    [
                      17
                      18
                    ]
                  ]
                ]
                nil
                nil
                nil
                nil
              ]
            ]
            [
              :body_stmt
              [
                [
                  :binary
                  [
                    :var_ref
                    [
                      :@ident
                      "a"
                      [
                        18
                        4
                      ]
                    ]
                  ]
                  :*
                  [
                    :var_ref
                    [
                      :@ident
                      "b"
                      [
                        18
                        8
                      ]
                    ]
                  ]
                ]
              ]
              nil
              nil
              nil
            ]
          ]
        ]
        nil
        nil
        nil
      ]
    ]
  ]
]
